language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: tomas.c.fox@gmail.com
  api_key:
    secure: qHTSmpcpPtm4RE5eo97DmTLQDN2DbtHlUlOl0hg7hkQwV+V56enWRRaVrVRMNieFBCj19cq1PxnptcKl2YRbdBCXIb4mmmuCu1CB9IiRWmomvCaf30EkNQWXHD5hzhhdvf5CtgGa37ddnX/FayfYfx46fZNScOzIlRPZaQbyWMeb12Duc3l0ORL+OwRrnWxAhiuyYEPUYJft2KdAZE8u7ItLfwxEIZD+2e0t1f7qj09lLl+RUCq+dlsMIuouYxt2U775q2xzkr80YnP64zp4Gg5m7EZYIC5dljj2R4Qaom41pE6E0+kLP1RxK7lmaZa1Ad66Pi+dETZ2RP3opXv0zcU+CazhveSigf9s5cLdUNE6jrDQ59UwX+fOy7QY9a1EMySqcSBo9MKnnaenQF/JPQ+l7bCCnwMs5row8JYoJh6cbo5HxrOLt6Uvi+dAekNVcRNnkQ/VRH/hIcL5OnnJX21OyqbWRWg6emRhDfbmu7eZwrlzpboJp8qceF2BrsjIPLfNJS7J45BkVYrTo+k24EnY51ECPSJ8lsGF+AcdXmUg5lSUjs3nQnLOmbpB24YiaCQdWAl929zbeluMK1u4pjHzDWAdhgSPzc/KZCGy46hf6s40qZ7ebnnwcT/aJ37uQhHkENGkiQVQk3SMmlI+zI+DCpFTM8c/zIF3nwPUriQ=
  on:
    tags: true
    repo: tfoxy/injular
